import { Droplets, Wind } from "lucide-react";
const Forecast = () => {
  const weatherData = {
    location: {
      name: "Virar",
      region: "Maharashtra",
      country: "India",
      lat: 19.4667,
      lon: 72.8,
      tz_id: "Asia/Kolkata",
      localtime_epoch: 1734354866,
      localtime: "2024-12-16 18:44",
    },
    current: {
      last_updated_epoch: 1734354000,
      last_updated: "2024-12-16 18:30",
      temp_c: 23.5,
      temp_f: 74.3,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 9.2,
      wind_kph: 14.8,
      wind_degree: 330,
      wind_dir: "NNW",
      pressure_mb: 1012,
      pressure_in: 29.87,
      precip_mm: 0,
      precip_in: 0,
      humidity: 53,
      cloud: 0,
      feelslike_c: 25,
      feelslike_f: 77,
      windchill_c: 23.5,
      windchill_f: 74.3,
      heatindex_c: 25,
      heatindex_f: 77,
      dewpoint_c: 13.3,
      dewpoint_f: 56,
      vis_km: 10,
      vis_miles: 6,
      uv: 0,
      gust_mph: 18.1,
      gust_kph: 29.2,
    },
    forecast: {
      forecastday: [
        {
          date: "2024-12-16",
          date_epoch: 1734307200,
          day: {
            maxtemp_c: 29.9,
            maxtemp_f: 85.8,
            mintemp_c: 20.3,
            mintemp_f: 68.5,
            avgtemp_c: 24.1,
            avgtemp_f: 75.3,
            maxwind_mph: 10.3,
            maxwind_kph: 16.6,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 36,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 1.5,
          },
          astro: {
            sunrise: "07:06 AM",
            sunset: "06:03 PM",
            moonrise: "07:01 PM",
            moonset: "08:00 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: 99,
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1734287400,
              time: "2024-12-16 00:00",
              temp_c: 22.4,
              temp_f: 72.3,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 83,
              wind_dir: "E",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 0,
              feelslike_c: 24.1,
              feelslike_f: 75.4,
              windchill_c: 22.4,
              windchill_f: 72.4,
              heatindex_c: 24.1,
              heatindex_f: 75.4,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.6,
              uv: 0,
            },
            {
              time_epoch: 1734291000,
              time: "2024-12-16 01:00",
              temp_c: 22.1,
              temp_f: 71.9,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 81,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 0,
              feelslike_c: 23.9,
              feelslike_f: 75.1,
              windchill_c: 22.2,
              windchill_f: 71.9,
              heatindex_c: 23.9,
              heatindex_f: 75.1,
              dewpoint_c: 7.1,
              dewpoint_f: 44.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.5,
              gust_kph: 12.1,
              uv: 0,
            },
            {
              time_epoch: 1734294600,
              time: "2024-12-16 02:00",
              temp_c: 21.8,
              temp_f: 71.2,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 86,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 21.8,
              feelslike_f: 71.2,
              windchill_c: 21.8,
              windchill_f: 71.2,
              heatindex_c: 23.8,
              heatindex_f: 74.8,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 0,
            },
            {
              time_epoch: 1734298200,
              time: "2024-12-16 03:00",
              temp_c: 21.4,
              temp_f: 70.6,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 94,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 35,
              cloud: 0,
              feelslike_c: 21.4,
              feelslike_f: 70.6,
              windchill_c: 21.4,
              windchill_f: 70.6,
              heatindex_c: 23.6,
              heatindex_f: 74.4,
              dewpoint_c: 5.5,
              dewpoint_f: 41.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 0,
            },
            {
              time_epoch: 1734301800,
              time: "2024-12-16 04:00",
              temp_c: 21,
              temp_f: 69.8,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 85,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 33,
              cloud: 0,
              feelslike_c: 21,
              feelslike_f: 69.8,
              windchill_c: 21,
              windchill_f: 69.8,
              heatindex_c: 23.3,
              heatindex_f: 73.9,
              dewpoint_c: 4.1,
              dewpoint_f: 39.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 0,
            },
            {
              time_epoch: 1734305400,
              time: "2024-12-16 05:00",
              temp_c: 20.6,
              temp_f: 69,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 75,
              wind_dir: "ENE",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 31,
              cloud: 0,
              feelslike_c: 20.6,
              feelslike_f: 69,
              windchill_c: 20.6,
              windchill_f: 69,
              heatindex_c: 20.6,
              heatindex_f: 69,
              dewpoint_c: 2.8,
              dewpoint_f: 37,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8,
              gust_kph: 12.9,
              uv: 0,
            },
            {
              time_epoch: 1734309000,
              time: "2024-12-16 06:00",
              temp_c: 20.3,
              temp_f: 68.5,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 72,
              wind_dir: "ENE",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 20.3,
              feelslike_f: 68.5,
              windchill_c: 20.3,
              windchill_f: 68.5,
              heatindex_c: 20.3,
              heatindex_f: 68.5,
              dewpoint_c: 2.2,
              dewpoint_f: 35.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 0,
            },
            {
              time_epoch: 1734312600,
              time: "2024-12-16 07:00",
              temp_c: 20.3,
              temp_f: 68.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 69,
              wind_dir: "ENE",
              pressure_mb: 1014,
              pressure_in: 29.94,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 20.3,
              feelslike_f: 68.6,
              windchill_c: 20.3,
              windchill_f: 68.6,
              heatindex_c: 20.3,
              heatindex_f: 68.6,
              dewpoint_c: 2.3,
              dewpoint_f: 36.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.6,
              uv: 0,
            },
            {
              time_epoch: 1734316200,
              time: "2024-12-16 08:00",
              temp_c: 22.5,
              temp_f: 72.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 91,
              wind_dir: "E",
              pressure_mb: 1015,
              pressure_in: 29.97,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 27,
              cloud: 0,
              feelslike_c: 23.2,
              feelslike_f: 73.7,
              windchill_c: 22.5,
              windchill_f: 72.4,
              heatindex_c: 23.2,
              heatindex_f: 73.7,
              dewpoint_c: 2.8,
              dewpoint_f: 37,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.7,
              gust_kph: 14.1,
              uv: 0.7,
            },
            {
              time_epoch: 1734319800,
              time: "2024-12-16 09:00",
              temp_c: 24.8,
              temp_f: 76.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 103,
              wind_dir: "ESE",
              pressure_mb: 1016,
              pressure_in: 29.99,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 24,
              cloud: 0,
              feelslike_c: 24.1,
              feelslike_f: 75.3,
              windchill_c: 24.8,
              windchill_f: 76.6,
              heatindex_c: 24.1,
              heatindex_f: 75.3,
              dewpoint_c: 2.9,
              dewpoint_f: 37.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.7,
              gust_kph: 12.3,
              uv: 2.1,
            },
            {
              time_epoch: 1734323400,
              time: "2024-12-16 10:00",
              temp_c: 27,
              temp_f: 80.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 106,
              wind_dir: "ESE",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 23,
              cloud: 0,
              feelslike_c: 25.5,
              feelslike_f: 77.9,
              windchill_c: 27,
              windchill_f: 80.6,
              heatindex_c: 25.5,
              heatindex_f: 77.9,
              dewpoint_c: 4.2,
              dewpoint_f: 39.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 4.1,
            },
            {
              time_epoch: 1734327000,
              time: "2024-12-16 11:00",
              temp_c: 28.8,
              temp_f: 83.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 74,
              wind_dir: "ENE",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 23,
              cloud: 0,
              feelslike_c: 27.1,
              feelslike_f: 80.7,
              windchill_c: 28.8,
              windchill_f: 83.9,
              heatindex_c: 27.1,
              heatindex_f: 80.7,
              dewpoint_c: 5.9,
              dewpoint_f: 42.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 2.7,
              gust_kph: 4.4,
              uv: 6,
            },
            {
              time_epoch: 1734330600,
              time: "2024-12-16 12:00",
              temp_c: 29.9,
              temp_f: 85.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2,
              wind_kph: 3.2,
              wind_degree: 324,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 21,
              cloud: 0,
              feelslike_c: 27.7,
              feelslike_f: 81.9,
              windchill_c: 29.9,
              windchill_f: 85.7,
              heatindex_c: 27.7,
              heatindex_f: 81.9,
              dewpoint_c: 5,
              dewpoint_f: 40.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 2.4,
              gust_kph: 3.9,
              uv: 6.9,
            },
            {
              time_epoch: 1734334200,
              time: "2024-12-16 13:00",
              temp_c: 29.9,
              temp_f: 85.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 20,
              cloud: 0,
              feelslike_c: 27.7,
              feelslike_f: 81.8,
              windchill_c: 29.9,
              windchill_f: 85.8,
              heatindex_c: 27.7,
              heatindex_f: 81.8,
              dewpoint_c: 4.6,
              dewpoint_f: 40.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 6.4,
            },
            {
              time_epoch: 1734337800,
              time: "2024-12-16 14:00",
              temp_c: 29.5,
              temp_f: 85,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 301,
              wind_dir: "WNW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 24,
              cloud: 0,
              feelslike_c: 27.7,
              feelslike_f: 81.8,
              windchill_c: 29.5,
              windchill_f: 85,
              heatindex_c: 27.7,
              heatindex_f: 81.8,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 4.8,
            },
            {
              time_epoch: 1734341400,
              time: "2024-12-16 15:00",
              temp_c: 28.3,
              temp_f: 83,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 310,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 29,
              cloud: 0,
              feelslike_c: 27.2,
              feelslike_f: 80.9,
              windchill_c: 28.3,
              windchill_f: 83,
              heatindex_c: 27.2,
              heatindex_f: 80.9,
              dewpoint_c: 8.7,
              dewpoint_f: 47.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.1,
              gust_kph: 21.1,
              uv: 2.7,
            },
            {
              time_epoch: 1734345000,
              time: "2024-12-16 16:00",
              temp_c: 27.2,
              temp_f: 81,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 317,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 35,
              cloud: 0,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 27.2,
              windchill_f: 81,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 10.6,
              dewpoint_f: 51.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.8,
              uv: 1,
            },
            {
              time_epoch: 1734348600,
              time: "2024-12-16 17:00",
              temp_c: 25.2,
              temp_f: 77.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 45,
              cloud: 0,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 25.2,
              windchill_f: 77.4,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 12.5,
              dewpoint_f: 54.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.4,
              gust_kph: 21.6,
              uv: 0.2,
            },
            {
              time_epoch: 1734352200,
              time: "2024-12-16 18:00",
              temp_c: 23.5,
              temp_f: 74.3,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 330,
              wind_dir: "NNW",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 53,
              cloud: 0,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 23.5,
              windchill_f: 74.3,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 13.3,
              dewpoint_f: 56,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.1,
              gust_kph: 29.2,
              uv: 0,
            },
            {
              time_epoch: 1734355800,
              time: "2024-12-16 19:00",
              temp_c: 22.8,
              temp_f: 73.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 338,
              wind_dir: "NNW",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 56,
              cloud: 0,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 22.8,
              windchill_f: 73.1,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: 13.6,
              dewpoint_f: 56.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 0,
            },
            {
              time_epoch: 1734359400,
              time: "2024-12-16 20:00",
              temp_c: 22.6,
              temp_f: 72.6,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 355,
              wind_dir: "N",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 55,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.4,
              windchill_c: 22.6,
              windchill_f: 72.6,
              heatindex_c: 24.7,
              heatindex_f: 76.4,
              dewpoint_c: 13.2,
              dewpoint_f: 55.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.2,
              gust_kph: 19.7,
              uv: 0,
            },
            {
              time_epoch: 1734363000,
              time: "2024-12-16 21:00",
              temp_c: 22.3,
              temp_f: 72.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 9,
              wind_dir: "N",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 52,
              cloud: 0,
              feelslike_c: 24.5,
              feelslike_f: 76.2,
              windchill_c: 22.3,
              windchill_f: 72.1,
              heatindex_c: 24.5,
              heatindex_f: 76.2,
              dewpoint_c: 12,
              dewpoint_f: 53.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.3,
              gust_kph: 18.1,
              uv: 0,
            },
            {
              time_epoch: 1734366600,
              time: "2024-12-16 22:00",
              temp_c: 22.1,
              temp_f: 71.7,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 13,
              wind_dir: "NNE",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 49,
              cloud: 0,
              feelslike_c: 24.4,
              feelslike_f: 75.9,
              windchill_c: 22.1,
              windchill_f: 71.7,
              heatindex_c: 24.4,
              heatindex_f: 75.9,
              dewpoint_c: 10.9,
              dewpoint_f: 51.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 0,
            },
            {
              time_epoch: 1734370200,
              time: "2024-12-16 23:00",
              temp_c: 21.7,
              temp_f: 71.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 26,
              wind_dir: "NNE",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 21.7,
              feelslike_f: 71.1,
              windchill_c: 21.7,
              windchill_f: 71.1,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 9.6,
              dewpoint_f: 49.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.9,
              gust_kph: 15.9,
              uv: 0,
            },
          ],
        },
        {
          date: "2024-12-17",
          date_epoch: 1734393600,
          day: {
            maxtemp_c: 27.9,
            maxtemp_f: 82.1,
            mintemp_c: 20,
            mintemp_f: 68,
            avgtemp_c: 23.2,
            avgtemp_f: 73.8,
            maxwind_mph: 10.1,
            maxwind_kph: 16.2,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 40,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 1.4,
          },
          astro: {
            sunrise: "07:06 AM",
            sunset: "06:04 PM",
            moonrise: "08:04 PM",
            moonset: "08:58 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: 96,
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1734373800,
              time: "2024-12-17 00:00",
              temp_c: 21.4,
              temp_f: 70.5,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 46,
              wind_dir: "NE",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 43,
              cloud: 0,
              feelslike_c: 21.4,
              feelslike_f: 70.5,
              windchill_c: 21.4,
              windchill_f: 70.5,
              heatindex_c: 24.1,
              heatindex_f: 75.3,
              dewpoint_c: 8.4,
              dewpoint_f: 47,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7,
              gust_kph: 11.3,
              uv: 0,
            },
            {
              time_epoch: 1734377400,
              time: "2024-12-17 01:00",
              temp_c: 21.1,
              temp_f: 70,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5,
              wind_degree: 49,
              wind_dir: "NE",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 41,
              cloud: 0,
              feelslike_c: 21.1,
              feelslike_f: 70,
              windchill_c: 21.1,
              windchill_f: 70,
              heatindex_c: 23.9,
              heatindex_f: 75.1,
              dewpoint_c: 7.5,
              dewpoint_f: 45.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.6,
              gust_kph: 10.6,
              uv: 0,
            },
            {
              time_epoch: 1734381000,
              time: "2024-12-17 02:00",
              temp_c: 20.9,
              temp_f: 69.5,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 41,
              wind_dir: "NE",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 20.9,
              feelslike_f: 69.5,
              windchill_c: 20.9,
              windchill_f: 69.5,
              heatindex_c: 20.9,
              heatindex_f: 69.5,
              dewpoint_c: 7,
              dewpoint_f: 44.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.1,
              gust_kph: 9.8,
              uv: 0,
            },
            {
              time_epoch: 1734384600,
              time: "2024-12-17 03:00",
              temp_c: 20.6,
              temp_f: 69.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5,
              wind_degree: 54,
              wind_dir: "NE",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 20.6,
              feelslike_f: 69.2,
              windchill_c: 20.6,
              windchill_f: 69.2,
              heatindex_c: 20.6,
              heatindex_f: 69.2,
              dewpoint_c: 6.6,
              dewpoint_f: 43.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.6,
              gust_kph: 10.6,
              uv: 0,
            },
            {
              time_epoch: 1734388200,
              time: "2024-12-17 04:00",
              temp_c: 20.4,
              temp_f: 68.7,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5,
              wind_degree: 58,
              wind_dir: "ENE",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 20.4,
              feelslike_f: 68.7,
              windchill_c: 20.4,
              windchill_f: 68.7,
              heatindex_c: 20.4,
              heatindex_f: 68.7,
              dewpoint_c: 6.3,
              dewpoint_f: 43.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.6,
              gust_kph: 10.6,
              uv: 0,
            },
            {
              time_epoch: 1734391800,
              time: "2024-12-17 05:00",
              temp_c: 20.2,
              temp_f: 68.4,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 38,
              wind_dir: "NE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 20.2,
              feelslike_f: 68.3,
              windchill_c: 20.2,
              windchill_f: 68.3,
              heatindex_c: 20.2,
              heatindex_f: 68.3,
              dewpoint_c: 6.1,
              dewpoint_f: 42.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.6,
              gust_kph: 9.1,
              uv: 0,
            },
            {
              time_epoch: 1734395400,
              time: "2024-12-17 06:00",
              temp_c: 20,
              temp_f: 68,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5,
              wind_degree: 54,
              wind_dir: "NE",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 20,
              feelslike_f: 68,
              windchill_c: 20,
              windchill_f: 68,
              heatindex_c: 20,
              heatindex_f: 68,
              dewpoint_c: 5.9,
              dewpoint_f: 42.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.6,
              gust_kph: 10.6,
              uv: 0,
            },
            {
              time_epoch: 1734399000,
              time: "2024-12-17 07:00",
              temp_c: 20.1,
              temp_f: 68.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 40,
              wind_dir: "NE",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 20.1,
              feelslike_f: 68.2,
              windchill_c: 20.1,
              windchill_f: 68.2,
              heatindex_c: 20.1,
              heatindex_f: 68.2,
              dewpoint_c: 6.1,
              dewpoint_f: 43.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.5,
              gust_kph: 12.1,
              uv: 0,
            },
            {
              time_epoch: 1734402600,
              time: "2024-12-17 08:00",
              temp_c: 21.9,
              temp_f: 71.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 79,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 21.9,
              feelslike_f: 71.4,
              windchill_c: 21.9,
              windchill_f: 71.4,
              heatindex_c: 23.8,
              heatindex_f: 74.8,
              dewpoint_c: 6.3,
              dewpoint_f: 43.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.3,
              gust_kph: 10.2,
              uv: 0.7,
            },
            {
              time_epoch: 1734406200,
              time: "2024-12-17 09:00",
              temp_c: 24,
              temp_f: 75.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 85,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 31,
              cloud: 0,
              feelslike_c: 24.2,
              feelslike_f: 75.6,
              windchill_c: 24,
              windchill_f: 75.2,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 6,
              dewpoint_f: 42.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5,
              gust_kph: 8,
              uv: 2.1,
            },
            {
              time_epoch: 1734409800,
              time: "2024-12-17 10:00",
              temp_c: 25.9,
              temp_f: 78.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2,
              wind_kph: 3.2,
              wind_degree: 58,
              wind_dir: "ENE",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 27,
              cloud: 0,
              feelslike_c: 25.1,
              feelslike_f: 77.1,
              windchill_c: 25.9,
              windchill_f: 78.6,
              heatindex_c: 25.1,
              heatindex_f: 77.1,
              dewpoint_c: 5.6,
              dewpoint_f: 42,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 2.4,
              gust_kph: 3.9,
              uv: 4.1,
            },
            {
              time_epoch: 1734413400,
              time: "2024-12-17 11:00",
              temp_c: 27.2,
              temp_f: 81,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 333,
              wind_dir: "NNW",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 25,
              cloud: 0,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 27.2,
              windchill_f: 81,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 5.8,
              dewpoint_f: 42.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 1.8,
              gust_kph: 2.9,
              uv: 5.8,
            },
            {
              time_epoch: 1734417000,
              time: "2024-12-17 12:00",
              temp_c: 27.9,
              temp_f: 82.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 293,
              wind_dir: "WNW",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 26,
              cloud: 0,
              feelslike_c: 26.5,
              feelslike_f: 79.7,
              windchill_c: 27.9,
              windchill_f: 82.1,
              heatindex_c: 26.5,
              heatindex_f: 79.7,
              dewpoint_c: 6.8,
              dewpoint_f: 44.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.6,
              gust_kph: 7.5,
              uv: 6.8,
            },
            {
              time_epoch: 1734420600,
              time: "2024-12-17 13:00",
              temp_c: 27.7,
              temp_f: 81.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 300,
              wind_dir: "WNW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 26.7,
              feelslike_f: 80,
              windchill_c: 27.7,
              windchill_f: 81.9,
              heatindex_c: 26.7,
              heatindex_f: 80,
              dewpoint_c: 8.6,
              dewpoint_f: 47.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.7,
              gust_kph: 14.1,
              uv: 5.7,
            },
            {
              time_epoch: 1734424200,
              time: "2024-12-17 14:00",
              temp_c: 27.3,
              temp_f: 81.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 33,
              cloud: 0,
              feelslike_c: 26.6,
              feelslike_f: 79.9,
              windchill_c: 27.3,
              windchill_f: 81.1,
              heatindex_c: 26.6,
              heatindex_f: 79.9,
              dewpoint_c: 9.7,
              dewpoint_f: 49.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11,
              gust_kph: 17.7,
              uv: 4.3,
            },
            {
              time_epoch: 1734427800,
              time: "2024-12-17 15:00",
              temp_c: 26.9,
              temp_f: 80.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1010,
              pressure_in: 29.82,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 26.5,
              feelslike_f: 79.7,
              windchill_c: 26.9,
              windchill_f: 80.4,
              heatindex_c: 26.5,
              heatindex_f: 79.7,
              dewpoint_c: 10.5,
              dewpoint_f: 50.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.7,
              gust_kph: 17.2,
              uv: 2.6,
            },
            {
              time_epoch: 1734431400,
              time: "2024-12-17 16:00",
              temp_c: 26.4,
              temp_f: 79.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 330,
              wind_dir: "NNW",
              pressure_mb: 1010,
              pressure_in: 29.82,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 0,
              feelslike_c: 26.3,
              feelslike_f: 79.3,
              windchill_c: 26.4,
              windchill_f: 79.4,
              heatindex_c: 26.3,
              heatindex_f: 79.3,
              dewpoint_c: 11.2,
              dewpoint_f: 52.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.9,
              gust_kph: 17.6,
              uv: 1,
            },
            {
              time_epoch: 1734435000,
              time: "2024-12-17 17:00",
              temp_c: 24.5,
              temp_f: 76.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 331,
              wind_dir: "NNW",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 47,
              cloud: 0,
              feelslike_c: 25.4,
              feelslike_f: 77.6,
              windchill_c: 24.5,
              windchill_f: 76.1,
              heatindex_c: 25.4,
              heatindex_f: 77.6,
              dewpoint_c: 12.4,
              dewpoint_f: 54.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.6,
              gust_kph: 25.1,
              uv: 0.2,
            },
            {
              time_epoch: 1734438600,
              time: "2024-12-17 18:00",
              temp_c: 22.8,
              temp_f: 73.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 337,
              wind_dir: "NNW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 53,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 22.8,
              windchill_f: 73.1,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 12.8,
              dewpoint_f: 55,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.1,
              gust_kph: 30.7,
              uv: 0,
            },
            {
              time_epoch: 1734442200,
              time: "2024-12-17 19:00",
              temp_c: 22.5,
              temp_f: 72.6,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 347,
              wind_dir: "NNW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 55,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.4,
              windchill_c: 22.5,
              windchill_f: 72.6,
              heatindex_c: 24.7,
              heatindex_f: 76.4,
              dewpoint_c: 12.9,
              dewpoint_f: 55.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.6,
              gust_kph: 28.3,
              uv: 0,
            },
            {
              time_epoch: 1734445800,
              time: "2024-12-17 20:00",
              temp_c: 22.4,
              temp_f: 72.3,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 358,
              wind_dir: "N",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 53,
              cloud: 0,
              feelslike_c: 24.6,
              feelslike_f: 76.3,
              windchill_c: 22.4,
              windchill_f: 72.4,
              heatindex_c: 24.6,
              heatindex_f: 76.3,
              dewpoint_c: 12.4,
              dewpoint_f: 54.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.7,
              gust_kph: 26.9,
              uv: 0,
            },
            {
              time_epoch: 1734449400,
              time: "2024-12-17 21:00",
              temp_c: 22.1,
              temp_f: 71.8,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 28,
              wind_dir: "NNE",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 49,
              cloud: 0,
              feelslike_c: 24.4,
              feelslike_f: 76,
              windchill_c: 22.1,
              windchill_f: 71.8,
              heatindex_c: 24.4,
              heatindex_f: 76,
              dewpoint_c: 11,
              dewpoint_f: 51.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 0,
            },
            {
              time_epoch: 1734453000,
              time: "2024-12-17 22:00",
              temp_c: 21.8,
              temp_f: 71.2,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 35,
              wind_dir: "NE",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 21.8,
              feelslike_f: 71.2,
              windchill_c: 21.8,
              windchill_f: 71.2,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 9.6,
              dewpoint_f: 49.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.8,
              gust_kph: 17.4,
              uv: 0,
            },
            {
              time_epoch: 1734456600,
              time: "2024-12-17 23:00",
              temp_c: 21.5,
              temp_f: 70.8,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 23,
              wind_dir: "NNE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 44,
              cloud: 0,
              feelslike_c: 21.6,
              feelslike_f: 70.8,
              windchill_c: 21.6,
              windchill_f: 70.8,
              heatindex_c: 24.2,
              heatindex_f: 75.5,
              dewpoint_c: 9,
              dewpoint_f: 48.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.3,
              gust_kph: 18.1,
              uv: 0,
            },
          ],
        },
      ],
    },
  };
  return (
    <>
      <div className="mx-auto h-screen mb-10 bg-white rounded-lg shadow-lg overflow-hidden">
        <div className="min-h-screen bg-gray-100 p-8">
          <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-lg overflow-hidden">
            <div className="p-8">
              <h1 className="text-3xl font-bold mb-4">
                {weatherData.location.name}, {weatherData.location.region}
              </h1>
              <p className="text-gray-600 mb-6">
                {weatherData.location.localtime.replace("T", "").split(" "[1])}
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="bg-blue-50 p-6 rounded-lg">
                  <div className="flex items-center justify-between mb-4">
                    <h2 className="text-2xl font-semibold">Current Weather</h2>
                    <img
                      src={weatherData.current.condition.icon}
                      alt={weatherData.current.condition.text}
                      className="w-16 h-16"
                    />
                  </div>
                  <p className="text-5xl font-bold mb-4">
                    {weatherData.current.temp_c}°C
                  </p>
                  <p className="text-xl mb-4">
                    {weatherData.current.condition.text}
                  </p>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="flex items-center">
                      <Droplets className="w-5 h-5 mr-2 text-blue-500" />
                      <span>{weatherData.current.humidity}% Humidity</span>
                    </div>
                    <div className="flex items-center">
                      <Wind className="w-5 h-5 mr-2 text-blue-500" />
                      <span>
                        {weatherData.current.wind_kph} km/h{" "}
                        {weatherData.current.wind_dir}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="bg-yellow-50 p-6 rounded-lg">
                  <h2 className="text-2xl font-semibold mb-4">
                    2-Day Forecast
                  </h2>
                  {weatherData.forecast.forecastday.map((day) => (
                    <div
                      key={day.date}
                      className="flex items-center justify-between mb-4 last:mb-0"
                    >
                      <div>
                        <p className="font-semibold">
                          {new Date(day.date).toLocaleDateString("en-US", {
                            weekday: "short",
                            month: "short",
                            day: "numeric",
                          })}
                        </p>
                        <p className="text-sm text-gray-600">
                          {day.day.condition.text}
                        </p>
                      </div>
                      <div className="flex items-center">
                        <img
                          src={day.day.condition.icon}
                          alt={day.day.condition.text}
                          className="w-10 h-10 mr-2"
                        />
                        <span>
                          {day.day.mintemp_c}°C - {day.day.maxtemp_c}°C
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Forecast;
