const Marine = () => {
  const weatherData = {
    location: {
      name: "Mumbai",
      region: "Maharashtra",
      country: "India",
      lat: 18.975,
      lon: 72.826,
      tz_id: "Asia/Kolkata",
      localtime_epoch: 1734356533,
      localtime: "2024-12-16 19:12",
    },
    forecast: {
      forecastday: [
        {
          date: "2024-12-16",
          date_epoch: 1734307200,
          day: {
            maxtemp_c: 25.7,
            maxtemp_f: 78.3,
            mintemp_c: 21.3,
            mintemp_f: 70.3,
            avgtemp_c: 24.4,
            avgtemp_f: 75.9,
            maxwind_mph: 7.9,
            maxwind_kph: 12.8,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 42,
            tides: [
              {
                tide: [
                  {
                    tide_time: "2024-12-16 00:27",
                    tide_height_mt: "4.80",
                    tide_type: "HIGH",
                  },
                  {
                    tide_time: "2024-12-16 06:34",
                    tide_height_mt: "1.60",
                    tide_type: "LOW",
                  },
                  {
                    tide_time: "2024-12-16 12:03",
                    tide_height_mt: "3.80",
                    tide_type: "HIGH",
                  },
                  {
                    tide_time: "2024-12-16 18:18",
                    tide_height_mt: "0.10",
                    tide_type: "LOW",
                  },
                ],
              },
            ],
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "07:05 AM",
            sunset: "06:04 PM",
            moonrise: "07:03 PM",
            moonset: "07:59 AM",
            moon_phase: "Full Moon",
            moon_illumination: 100,
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1734287400,
              time: "2024-12-16 00:00",
              temp_c: 25.7,
              temp_f: 78.3,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 66,
              wind_dir: "ENE",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 52,
              cloud: 0,
              feelslike_c: 26.5,
              feelslike_f: 79.7,
              windchill_c: 25.7,
              windchill_f: 78.3,
              heatindex_c: 26.5,
              heatindex_f: 79.7,
              dewpoint_c: 15.2,
              dewpoint_f: 59.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.6,
              gust_kph: 13.9,
              uv: 1,
              sig_ht_mt: 0.2,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.8,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 3.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734291000,
              time: "2024-12-16 01:00",
              temp_c: 25.2,
              temp_f: 77.4,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 96,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 48,
              cloud: 0,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 25.2,
              windchill_f: 77.4,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 13.6,
              dewpoint_f: 56.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.4,
              gust_kph: 16.7,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 3.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734294600,
              time: "2024-12-16 02:00",
              temp_c: 24.7,
              temp_f: 76.5,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 89,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 44,
              cloud: 0,
              feelslike_c: 25.4,
              feelslike_f: 77.7,
              windchill_c: 24.7,
              windchill_f: 76.5,
              heatindex_c: 25.4,
              heatindex_f: 77.7,
              dewpoint_c: 11.7,
              dewpoint_f: 53.1,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10,
              gust_kph: 16,
              uv: 1,
              sig_ht_mt: 0.4,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.2,
              swell_dir: 235,
              swell_dir_16_point: "SW",
              swell_period_secs: 13.3,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734298200,
              time: "2024-12-16 03:00",
              temp_c: 24.3,
              temp_f: 75.7,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 87,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 42,
              cloud: 0,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 24.3,
              windchill_f: 75.7,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 10.4,
              dewpoint_f: 50.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.5,
              gust_kph: 20.1,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 3.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734301800,
              time: "2024-12-16 04:00",
              temp_c: 24,
              temp_f: 75.2,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 86,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 39,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 24,
              windchill_f: 75.2,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 9.1,
              dewpoint_f: 48.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.4,
              gust_kph: 23.1,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 3.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734305400,
              time: "2024-12-16 05:00",
              temp_c: 23.7,
              temp_f: 74.7,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 87,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 24.5,
              feelslike_f: 76.1,
              windchill_c: 23.7,
              windchill_f: 74.7,
              heatindex_c: 24.5,
              heatindex_f: 76.1,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.7,
              gust_kph: 22,
              uv: 1,
              sig_ht_mt: 0.5,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 241,
              swell_dir_16_point: "WSW",
              swell_period_secs: 13.2,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734309000,
              time: "2024-12-16 06:00",
              temp_c: 23.4,
              temp_f: 74.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 86,
              wind_dir: "E",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 24.3,
              feelslike_f: 75.8,
              windchill_c: 23.4,
              windchill_f: 74.1,
              heatindex_c: 24.3,
              heatindex_f: 75.8,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.3,
              gust_kph: 21.4,
              uv: 1,
              sig_ht_mt: 0.4,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 13.3,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734312600,
              time: "2024-12-16 07:00",
              temp_c: 23.2,
              temp_f: 73.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 84,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 24.2,
              feelslike_f: 75.6,
              windchill_c: 23.2,
              windchill_f: 73.8,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 7.6,
              dewpoint_f: 45.7,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 6,
              sig_ht_mt: 0.4,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 13.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734316200,
              time: "2024-12-16 08:00",
              temp_c: 23.6,
              temp_f: 74.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 85,
              wind_dir: "E",
              pressure_mb: 1015,
              pressure_in: 29.97,
              precip_mm: 0,
              precip_in: 0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 24.3,
              feelslike_f: 75.8,
              windchill_c: 23.6,
              windchill_f: 74.5,
              heatindex_c: 24.3,
              heatindex_f: 75.8,
              dewpoint_c: 7.5,
              dewpoint_f: 45.6,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13,
              gust_kph: 20.8,
              uv: 6,
              sig_ht_mt: 0.5,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.2,
              swell_dir: 242,
              swell_dir_16_point: "WSW",
              swell_period_secs: 13.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734319800,
              time: "2024-12-16 09:00",
              temp_c: 24.1,
              temp_f: 75.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 90,
              wind_dir: "E",
              pressure_mb: 1016,
              pressure_in: 29.99,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 0,
              feelslike_c: 24.5,
              feelslike_f: 76.1,
              windchill_c: 24.1,
              windchill_f: 75.4,
              heatindex_c: 24.5,
              heatindex_f: 76.1,
              dewpoint_c: 7.5,
              dewpoint_f: 45.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.1,
              gust_kph: 19.5,
              uv: 6,
              sig_ht_mt: 0.4,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 239,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.9,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734323400,
              time: "2024-12-16 10:00",
              temp_c: 24.8,
              temp_f: 76.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 86,
              wind_dir: "E",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 32,
              cloud: 0,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 24.8,
              windchill_f: 76.6,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: 7.2,
              dewpoint_f: 44.9,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.3,
              gust_kph: 18.3,
              uv: 6,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 239,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734327000,
              time: "2024-12-16 11:00",
              temp_c: 21.3,
              temp_f: 70.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 86,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 21.3,
              feelslike_f: 70.3,
              windchill_c: 21.3,
              windchill_f: 70.3,
              heatindex_c: 23.1,
              heatindex_f: 73.6,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.2,
              gust_kph: 19.7,
              uv: 6,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.3,
              swell_ht_ft: 1.1,
              swell_dir: 242,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.5,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734330600,
              time: "2024-12-16 12:00",
              temp_c: 22.6,
              temp_f: 72.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 89,
              wind_dir: "E",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 28,
              cloud: 0,
              feelslike_c: 23.3,
              feelslike_f: 73.9,
              windchill_c: 22.6,
              windchill_f: 72.7,
              heatindex_c: 23.3,
              heatindex_f: 73.9,
              dewpoint_c: 3,
              dewpoint_f: 37.5,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.7,
              gust_kph: 7.6,
              uv: 6,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 239,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.7,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734334200,
              time: "2024-12-16 13:00",
              temp_c: 23.4,
              temp_f: 74.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.8,
              wind_kph: 2.9,
              wind_degree: 217,
              wind_dir: "SW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 26,
              cloud: 0,
              feelslike_c: 23.5,
              feelslike_f: 74.3,
              windchill_c: 23.4,
              windchill_f: 74.1,
              heatindex_c: 23.5,
              heatindex_f: 74.3,
              dewpoint_c: 2.9,
              dewpoint_f: 37.3,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 3.8,
              gust_kph: 6,
              uv: 6,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 239,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.6,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734337800,
              time: "2024-12-16 14:00",
              temp_c: 24.2,
              temp_f: 75.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 277,
              wind_dir: "W",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 29,
              cloud: 0,
              feelslike_c: 24.2,
              feelslike_f: 75.5,
              windchill_c: 24.2,
              windchill_f: 75.6,
              heatindex_c: 24.2,
              heatindex_f: 75.5,
              dewpoint_c: 5,
              dewpoint_f: 40.9,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.6,
              uv: 6,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.2,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.2,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734341400,
              time: "2024-12-16 15:00",
              temp_c: 24.8,
              temp_f: 76.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 301,
              wind_dir: "WNW",
              pressure_mb: 1010,
              pressure_in: 29.84,
              precip_mm: 0,
              precip_in: 0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 24.8,
              windchill_f: 76.6,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 8.6,
              dewpoint_f: 47.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.9,
              gust_kph: 27.2,
              uv: 6,
              sig_ht_mt: 0.4,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 239,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.6,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734345000,
              time: "2024-12-16 16:00",
              temp_c: 24.9,
              temp_f: 76.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 313,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.84,
              precip_mm: 0,
              precip_in: 0,
              humidity: 43,
              cloud: 0,
              feelslike_c: 25.5,
              feelslike_f: 77.8,
              windchill_c: 24.9,
              windchill_f: 76.8,
              heatindex_c: 25.5,
              heatindex_f: 77.8,
              dewpoint_c: 11.5,
              dewpoint_f: 52.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.5,
              gust_kph: 26.6,
              uv: 6,
              sig_ht_mt: 0.6,
              swell_ht_mt: 0.3,
              swell_ht_ft: 0.9,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.5,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734348600,
              time: "2024-12-16 17:00",
              temp_c: 24.8,
              temp_f: 76.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 322,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 47,
              cloud: 0,
              feelslike_c: 25.6,
              feelslike_f: 78.1,
              windchill_c: 24.8,
              windchill_f: 76.6,
              heatindex_c: 25.6,
              heatindex_f: 78.1,
              dewpoint_c: 12.9,
              dewpoint_f: 55.2,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.1,
              gust_kph: 25.9,
              uv: 6,
              sig_ht_mt: 0.7,
              swell_ht_mt: 0.5,
              swell_ht_ft: 1.6,
              swell_dir: 241,
              swell_dir_16_point: "WSW",
              swell_period_secs: 21.4,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734352200,
              time: "2024-12-16 18:00",
              temp_c: 25,
              temp_f: 77,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 325,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 51,
              cloud: 0,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 25,
              windchill_f: 77,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 14.1,
              dewpoint_f: 57.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.8,
              gust_kph: 23.8,
              uv: 1,
              sig_ht_mt: 0.7,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.5,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734355800,
              time: "2024-12-16 19:00",
              temp_c: 25.4,
              temp_f: 77.7,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 13.9,
              wind_kph: 22.3,
              wind_degree: 331,
              wind_dir: "NNW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 0,
              feelslike_c: 26.3,
              feelslike_f: 79.4,
              windchill_c: 25.4,
              windchill_f: 77.7,
              heatindex_c: 26.3,
              heatindex_f: 79.4,
              dewpoint_c: 15.4,
              dewpoint_f: 59.7,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.6,
              gust_kph: 37.9,
              uv: 1,
              sig_ht_mt: 0.8,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.4,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734359400,
              time: "2024-12-16 20:00",
              temp_c: 25.7,
              temp_f: 78.3,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 11.4,
              wind_kph: 18.4,
              wind_degree: 337,
              wind_dir: "NNW",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 56,
              cloud: 0,
              feelslike_c: 26.7,
              feelslike_f: 80,
              windchill_c: 25.7,
              windchill_f: 78.3,
              heatindex_c: 26.7,
              heatindex_f: 80,
              dewpoint_c: 16.3,
              dewpoint_f: 61.3,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18,
              gust_kph: 28.9,
              uv: 1,
              sig_ht_mt: 0.6,
              swell_ht_mt: 0.5,
              swell_ht_ft: 1.6,
              swell_dir: 242,
              swell_dir_16_point: "WSW",
              swell_period_secs: 21.4,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734363000,
              time: "2024-12-16 21:00",
              temp_c: 25.6,
              temp_f: 78.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 353,
              wind_dir: "N",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 0,
              feelslike_c: 26.6,
              feelslike_f: 79.8,
              windchill_c: 25.6,
              windchill_f: 78.1,
              heatindex_c: 26.6,
              heatindex_f: 79.8,
              dewpoint_c: 16,
              dewpoint_f: 60.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.5,
              gust_kph: 21.7,
              uv: 1,
              sig_ht_mt: 0.4,
              swell_ht_mt: 0.3,
              swell_ht_ft: 1,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.2,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734366600,
              time: "2024-12-16 22:00",
              temp_c: 25.4,
              temp_f: 77.7,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 4,
              wind_dir: "N",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 0,
              feelslike_c: 26.3,
              feelslike_f: 79.4,
              windchill_c: 25.4,
              windchill_f: 77.7,
              heatindex_c: 26.3,
              heatindex_f: 79.4,
              dewpoint_c: 15.5,
              dewpoint_f: 59.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.6,
              gust_kph: 18.6,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.3,
              swell_ht_ft: 0.9,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 12.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734370200,
              time: "2024-12-16 23:00",
              temp_c: 25.1,
              temp_f: 77.2,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 9,
              wind_dir: "N",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 51,
              cloud: 0,
              feelslike_c: 26,
              feelslike_f: 78.7,
              windchill_c: 25.1,
              windchill_f: 77.2,
              heatindex_c: 26,
              heatindex_f: 78.7,
              dewpoint_c: 14.3,
              dewpoint_f: 57.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 241,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.7,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
          ],
        },
        {
          date: "2024-12-17",
          date_epoch: 1734393600,
          day: {
            maxtemp_c: 25.2,
            maxtemp_f: 77.4,
            mintemp_c: 21.3,
            mintemp_f: 70.3,
            avgtemp_c: 23.9,
            avgtemp_f: 75.1,
            maxwind_mph: 6.6,
            maxwind_kph: 10.5,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 45,
            tides: [
              {
                tide: [
                  {
                    tide_time: "2024-12-17 01:09",
                    tide_height_mt: "4.70",
                    tide_type: "HIGH",
                  },
                  {
                    tide_time: "2024-12-17 07:20",
                    tide_height_mt: "1.60",
                    tide_type: "LOW",
                  },
                  {
                    tide_time: "2024-12-17 12:48",
                    tide_height_mt: "3.70",
                    tide_type: "HIGH",
                  },
                  {
                    tide_time: "2024-12-17 18:59",
                    tide_height_mt: "0.30",
                    tide_type: "LOW",
                  },
                ],
              },
            ],
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "07:05 AM",
            sunset: "06:05 PM",
            moonrise: "08:06 PM",
            moonset: "08:57 AM",
            moon_phase: "Waxing Gibbous",
            moon_illumination: 86,
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1734373800,
              time: "2024-12-17 00:00",
              temp_c: 25.1,
              temp_f: 77.2,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 15,
              wind_dir: "NNE",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 48,
              cloud: 0,
              feelslike_c: 25.8,
              feelslike_f: 78.5,
              windchill_c: 25.1,
              windchill_f: 77.2,
              heatindex_c: 25.8,
              heatindex_f: 78.5,
              dewpoint_c: 13.5,
              dewpoint_f: 56.3,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.8,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734377400,
              time: "2024-12-17 01:00",
              temp_c: 24.8,
              temp_f: 76.6,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 25,
              wind_dir: "NNE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 25.5,
              feelslike_f: 78,
              windchill_c: 24.8,
              windchill_f: 76.6,
              heatindex_c: 25.5,
              heatindex_f: 78,
              dewpoint_c: 12.5,
              dewpoint_f: 54.5,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.5,
              gust_kph: 8.9,
              uv: 1,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734381000,
              time: "2024-12-17 02:00",
              temp_c: 24.5,
              temp_f: 76.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 50,
              wind_dir: "NE",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 25.3,
              feelslike_f: 77.6,
              windchill_c: 24.5,
              windchill_f: 76.1,
              heatindex_c: 25.3,
              heatindex_f: 77.6,
              dewpoint_c: 12.1,
              dewpoint_f: 53.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 3.4,
              gust_kph: 5.5,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 239,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19.7,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734384600,
              time: "2024-12-17 03:00",
              temp_c: 24.2,
              temp_f: 75.6,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 30,
              wind_dir: "NNE",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 45,
              cloud: 0,
              feelslike_c: 25.1,
              feelslike_f: 77.3,
              windchill_c: 24.2,
              windchill_f: 75.6,
              heatindex_c: 25.1,
              heatindex_f: 77.3,
              dewpoint_c: 11.7,
              dewpoint_f: 53,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 3.4,
              gust_kph: 5.5,
              uv: 1,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734388200,
              time: "2024-12-17 04:00",
              temp_c: 24,
              temp_f: 75.2,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 72,
              wind_dir: "ENE",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 25,
              feelslike_f: 77.1,
              windchill_c: 24,
              windchill_f: 75.2,
              heatindex_c: 25,
              heatindex_f: 77.1,
              dewpoint_c: 11.6,
              dewpoint_f: 52.9,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.1,
              gust_kph: 6.6,
              uv: 1,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734391800,
              time: "2024-12-17 05:00",
              temp_c: 23.7,
              temp_f: 74.7,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 96,
              wind_dir: "E",
              pressure_mb: 1011,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 24.9,
              feelslike_f: 76.8,
              windchill_c: 23.7,
              windchill_f: 74.7,
              heatindex_c: 24.9,
              heatindex_f: 76.8,
              dewpoint_c: 11.3,
              dewpoint_f: 52.3,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.5,
              gust_kph: 8.8,
              uv: 1,
              sig_ht_mt: 0.5,
              swell_ht_mt: 0.5,
              swell_ht_ft: 1.5,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19.5,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734395400,
              time: "2024-12-17 06:00",
              temp_c: 23.4,
              temp_f: 74.1,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 81,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 45,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 23.4,
              windchill_f: 74.1,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 10.7,
              dewpoint_f: 51.2,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.5,
              gust_kph: 8.9,
              uv: 1,
              sig_ht_mt: 0.2,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.7,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734399000,
              time: "2024-12-17 07:00",
              temp_c: 23.2,
              temp_f: 73.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 83,
              wind_dir: "E",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 44,
              cloud: 0,
              feelslike_c: 24.6,
              feelslike_f: 76.3,
              windchill_c: 23.2,
              windchill_f: 73.8,
              heatindex_c: 24.6,
              heatindex_f: 76.3,
              dewpoint_c: 10.2,
              dewpoint_f: 50.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.5,
              gust_kph: 10.5,
              uv: 6,
              sig_ht_mt: 0.2,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 246,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.7,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734402600,
              time: "2024-12-17 08:00",
              temp_c: 23.4,
              temp_f: 74.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 83,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 42,
              cloud: 0,
              feelslike_c: 24.6,
              feelslike_f: 76.3,
              windchill_c: 23.4,
              windchill_f: 74.1,
              heatindex_c: 24.6,
              heatindex_f: 76.3,
              dewpoint_c: 9.9,
              dewpoint_f: 49.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.8,
              gust_kph: 10.9,
              uv: 6,
              sig_ht_mt: 0.5,
              swell_ht_mt: 0.5,
              swell_ht_ft: 1.5,
              swell_dir: 241,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19.5,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734406200,
              time: "2024-12-17 09:00",
              temp_c: 23.8,
              temp_f: 74.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 96,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 41,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 23.8,
              windchill_f: 74.8,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 9.6,
              dewpoint_f: 49.3,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.7,
              gust_kph: 12.3,
              uv: 6,
              sig_ht_mt: 0.2,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 2.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734409800,
              time: "2024-12-17 10:00",
              temp_c: 24.3,
              temp_f: 75.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 81,
              wind_dir: "E",
              pressure_mb: 1014,
              pressure_in: 29.94,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 24.3,
              windchill_f: 75.7,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: 8.7,
              dewpoint_f: 47.6,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.4,
              gust_kph: 8.7,
              uv: 6,
              sig_ht_mt: 0.2,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19.1,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734413400,
              time: "2024-12-17 11:00",
              temp_c: 22.9,
              temp_f: 73.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.5,
              wind_kph: 4,
              wind_degree: 105,
              wind_dir: "ESE",
              pressure_mb: 1013,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 0,
              feelslike_c: 23.9,
              feelslike_f: 75.1,
              windchill_c: 22.9,
              windchill_f: 73.2,
              heatindex_c: 23.9,
              heatindex_f: 75.1,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.6,
              gust_kph: 7.5,
              uv: 6,
              sig_ht_mt: 0.4,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 241,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19.5,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734417000,
              time: "2024-12-17 12:00",
              temp_c: 21.3,
              temp_f: 70.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.1,
              wind_kph: 1.8,
              wind_degree: 211,
              wind_dir: "SSW",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 33,
              cloud: 0,
              feelslike_c: 21.3,
              feelslike_f: 70.3,
              windchill_c: 21.3,
              windchill_f: 70.3,
              heatindex_c: 23.4,
              heatindex_f: 74.1,
              dewpoint_c: 4.6,
              dewpoint_f: 40.2,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 2.3,
              gust_kph: 3.8,
              uv: 6,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.6,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734420600,
              time: "2024-12-17 13:00",
              temp_c: 22.1,
              temp_f: 71.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 289,
              wind_dir: "WNW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 23.8,
              feelslike_f: 74.9,
              windchill_c: 22.1,
              windchill_f: 71.8,
              heatindex_c: 23.8,
              heatindex_f: 74.9,
              dewpoint_c: 6.5,
              dewpoint_f: 43.7,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.6,
              uv: 6,
              sig_ht_mt: 0.1,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.7,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734424200,
              time: "2024-12-17 14:00",
              temp_c: 23.1,
              temp_f: 73.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              humidity: 41,
              cloud: 0,
              feelslike_c: 24.4,
              feelslike_f: 76,
              windchill_c: 23.1,
              windchill_f: 73.6,
              heatindex_c: 24.4,
              heatindex_f: 76,
              dewpoint_c: 9.2,
              dewpoint_f: 48.5,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.8,
              gust_kph: 30.2,
              uv: 6,
              sig_ht_mt: 0.5,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 241,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734427800,
              time: "2024-12-17 15:00",
              temp_c: 23.5,
              temp_f: 74.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 314,
              wind_dir: "NW",
              pressure_mb: 1010,
              pressure_in: 29.82,
              precip_mm: 0,
              precip_in: 0,
              humidity: 44,
              cloud: 0,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 23.5,
              windchill_f: 74.3,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: 10.7,
              dewpoint_f: 51.3,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.7,
              gust_kph: 33.3,
              uv: 6,
              sig_ht_mt: 0.5,
              swell_ht_mt: 0.2,
              swell_ht_ft: 0.8,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 19,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734431400,
              time: "2024-12-17 16:00",
              temp_c: 23.9,
              temp_f: 75,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 321,
              wind_dir: "NW",
              pressure_mb: 1010,
              pressure_in: 29.82,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 23.9,
              windchill_f: 75,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 11.7,
              dewpoint_f: 53,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.3,
              gust_kph: 32.7,
              uv: 6,
              sig_ht_mt: 0.6,
              swell_ht_mt: 0.3,
              swell_ht_ft: 1,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 18.9,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734435000,
              time: "2024-12-17 17:00",
              temp_c: 24,
              temp_f: 75.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 326,
              wind_dir: "NNW",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 0,
              feelslike_c: 25.2,
              feelslike_f: 77.3,
              windchill_c: 24,
              windchill_f: 75.2,
              heatindex_c: 25.2,
              heatindex_f: 77.3,
              dewpoint_c: 12.8,
              dewpoint_f: 55,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.5,
              gust_kph: 33,
              uv: 6,
              sig_ht_mt: 0.6,
              swell_ht_mt: 0.5,
              swell_ht_ft: 1.5,
              swell_dir: 239,
              swell_dir_16_point: "WSW",
              swell_period_secs: 17.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734438600,
              time: "2024-12-17 18:00",
              temp_c: 24.1,
              temp_f: 75.4,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 330,
              wind_dir: "NNW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 0,
              feelslike_c: 25.4,
              feelslike_f: 77.6,
              windchill_c: 24.1,
              windchill_f: 75.4,
              heatindex_c: 25.4,
              heatindex_f: 77.6,
              dewpoint_c: 14,
              dewpoint_f: 57.2,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 22.8,
              gust_kph: 36.6,
              uv: 1,
              sig_ht_mt: 0.7,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.2,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 18.7,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734442200,
              time: "2024-12-17 19:00",
              temp_c: 24.7,
              temp_f: 76.5,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 15.7,
              wind_kph: 25.2,
              wind_degree: 333,
              wind_dir: "NNW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 0,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 24.7,
              windchill_f: 76.5,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 15,
              dewpoint_f: 58.9,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 25.2,
              gust_kph: 40.6,
              uv: 1,
              sig_ht_mt: 0.9,
              swell_ht_mt: 0.5,
              swell_ht_ft: 1.5,
              swell_dir: 244,
              swell_dir_16_point: "WSW",
              swell_period_secs: 18.3,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734445800,
              time: "2024-12-17 20:00",
              temp_c: 25.2,
              temp_f: 77.4,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 13.4,
              wind_kph: 21.6,
              wind_degree: 341,
              wind_dir: "NNW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 0,
              feelslike_c: 26.2,
              feelslike_f: 79.1,
              windchill_c: 25.2,
              windchill_f: 77.4,
              heatindex_c: 26.2,
              heatindex_f: 79.1,
              dewpoint_c: 15.2,
              dewpoint_f: 59.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.7,
              gust_kph: 33.3,
              uv: 1,
              sig_ht_mt: 0.6,
              swell_ht_mt: 0.6,
              swell_ht_ft: 1.9,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 17.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734449400,
              time: "2024-12-17 21:00",
              temp_c: 25.2,
              temp_f: 77.4,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 11,
              wind_kph: 17.6,
              wind_degree: 359,
              wind_dir: "N",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 0,
              feelslike_c: 26.1,
              feelslike_f: 79,
              windchill_c: 25.2,
              windchill_f: 77.4,
              heatindex_c: 26.1,
              heatindex_f: 79,
              dewpoint_c: 14.9,
              dewpoint_f: 58.8,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17,
              gust_kph: 27.4,
              uv: 1,
              sig_ht_mt: 0.5,
              swell_ht_mt: 0.4,
              swell_ht_ft: 1.3,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 17.9,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734453000,
              time: "2024-12-17 22:00",
              temp_c: 25.2,
              temp_f: 77.4,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 13,
              wind_dir: "NNE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 0,
              feelslike_c: 26,
              feelslike_f: 78.8,
              windchill_c: 25.2,
              windchill_f: 77.4,
              heatindex_c: 26,
              heatindex_f: 78.8,
              dewpoint_c: 14.1,
              dewpoint_f: 57.4,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.6,
              gust_kph: 20.3,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.3,
              swell_ht_ft: 1.1,
              swell_dir: 245,
              swell_dir_16_point: "WSW",
              swell_period_secs: 3.8,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
            {
              time_epoch: 1734456600,
              time: "2024-12-17 23:00",
              temp_c: 24.9,
              temp_f: 76.8,
              is_day: 0,
              condition: {
                text: "Clear ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 32,
              wind_dir: "NNE",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 0,
              feelslike_c: 25.7,
              feelslike_f: 78.3,
              windchill_c: 24.9,
              windchill_f: 76.8,
              heatindex_c: 25.7,
              heatindex_f: 78.3,
              dewpoint_c: 13.4,
              dewpoint_f: 56,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 1,
              sig_ht_mt: 0.3,
              swell_ht_mt: 0.6,
              swell_ht_ft: 1.9,
              swell_dir: 240,
              swell_dir_16_point: "WSW",
              swell_period_secs: 3.9,
              water_temp_c: 26.7,
              water_temp_f: 80.1,
            },
          ],
        },
      ],
    },
  };
  return (
    <div className="min-h-screen bg-gray-100 p-4 rounded-lg cursor-pointer">
      <div className=" bg-gray-100 p-8">
        <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-lg overflow-hidden">
          <div className="p-8">
            <h1 className="text-4xl font-bold text-gray-800 mb-4">
              {weatherData.location.name}
            </h1>
            <p className="text-gray-600 mb-8">
              {weatherData.location.region}, {weatherData.location.country}
            </p>

            <div className="border-t border-gray-200 pt-8">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                Forecast
              </h2>
              <div className="flex justify-between">
                {weatherData.forecast.forecastday.map((day, index) => (
                  <div key={index} className="text-center">
                    <p className="text-gray-600 mb-2">
                      {new Date(day.date).toLocaleDateString("en-US", {
                        weekday: "short",
                      })}
                    </p>
                    <img
                      src={day.day.condition.icon}
                      alt={day.day.condition.text}
                      className="w-12 h-12 mx-auto mb-2"
                    />
                    <p className="text-lg font-semibold text-gray-800">
                      {day.day.maxtemp_c}°C
                    </p>
                    <p className="text-sm text-gray-600">
                      {day.day.mintemp_c}°C
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Marine;
